const blogData = [
    {
      "id": "N001",
      "category1": "Agriculture",
      "category2": "Farm",
      "title": "How to optimize all your farm inputs for great efficiency during low commodity prices times! ",
      "image_source": "/image35.jpg", 
      "image_alt": "Farmer inspecting carrots, representing AI farming",
      "link": "/news/ai-vertical-farming-funding",
      "description":"When a producer evaluates what is necessary to grow a good crop, there are very few inputs that can be forgone.  At that point, our objective is to make sure every necessary input is applied at a proper rate at the proper time our focus needs to be on efficiency.",
    },
    {
      "id": "N002",
      "category1": "Field",
      "category2": "Tax",
      "title": "Tax deductions available for residual fertility on purchased land beneficial ownership. ",
      "image_source": "/image36.jpg", 
      "image_alt": "Parched land with a green sprout, representing drought resistance",
      "link": "/news/drought-resistant-crops",
      "description":"When farmland is purchased, tax code allows the purchaser to deduct the value of the excess fertility in the field like other improvements on the ground, such that point, our objective is to make every necessary input is applied at a proper rate at the proper time our focus needs to be.",
    },
    {
      "id": "N003",
      "category1": "Agriculture",
      "category2": "Food",
      "title": "Can urban agriculture feed our cities sustainably? Insights from experts around the world!! ",
      "image_source": "/image37.jpg",
      "image_alt": "Robotic arm picking apples in an orchard",
      "link": "/news/robotics-fruit-picking",
      "description":"In a typical food network model, you buy a share before planting, this enables the farmer to purchase seeds, compost and technology without taking out loans our objective is to make sure every necessary input is applied at a proper rate at the proper time our focus needs to be.",
    },
    {
      "id": "N004",
      "category1": "Solar panels",
      "category2": "Strawberry",
      "title": "Strawberries in the sun: How can solar panels boost berries and cut the harming emissions!! ",
      "image_source": "/image48.jpg",
      "image_alt": "Farmer spreading fertilizer in a field",
      "link": "/news/fertilizer-prices-impact",
      "description":"Using a solar modeling tool, researchers estimated all the electricity potential of strawberry farms if they installed solar panels with transparency levels...",
    },
    {
      "id": "N005",
      "category1": "Climate",
      "category2": "Food",
      "title": "What impact does the climate change have on agriculture? A look into the future effects! ",
      "image_source": "/image39.jpg",
      "image_alt": "Basket full of fresh organic vegetables",
      "link": "/news/organic-demand-growth",
      "description":"Climate change is reshaping the way food is grown, rising temperatures and unpredictable weather make traditional approaches less reliable, which...",
    },
    {
      "id": "N006",
      "category1": "Agriculture",
      "category2": "Gardens",
      "title": "Why urban agriculture must be central to real estate and smart planning around the world? ",
      "image_source": "/image40.jpg",
      "image_alt": "Hands shaking over a world map, symbolizing trade",
      "link": "/news/agri-trade-agreements",
      "description":"Modern urban agriculture is not about hobby gardens or aesthetic green roofs, it’s about controlled agriculture, rooftop and vertical farming and landscape...",
    },
 
  ];
  
  export default blogData;