const newsData = [
    {
      "id": "N001",
      "category1": "AI Farming",
      "category2": "Food",
      "title": "AI food driven vertical farming project secures huge funding",
      "image_source": "/image35.jpg", 
      "image_alt": "Farmer inspecting carrots, representing AI farming",
      "link": "/news/ai-vertical-farming-funding",
    },
    {
      "id": "N002",
      "category1": "Sustainability",
      "category2": "Water",
      "title": "New drought-resistant crop varieties promise future food security",
      "image_source": "/image36.jpg", 
      "image_alt": "Parched land with a green sprout, representing drought resistance",
      "link": "/news/drought-resistant-crops",
    },
    {
      "id": "N003",
      "category1": "Technology",
      "category2": "Harvest",
      "title": "Robotics revolutionizing fruit picking efficiency in orchards",
      "image_source": "/image37.jpg",
      "image_alt": "Robotic arm picking apples in an orchard",
      "link": "/news/robotics-fruit-picking",
    },
    {
      "id": "N004",
      "category1": "Agribusiness",
      "category2": "Market",
      "title": "Global fertilizer prices impact planting decisions worldwide",
      "image_source": "/image38.jpg",
      "image_alt": "Farmer spreading fertilizer in a field",
      "link": "/news/fertilizer-prices-impact",
    },
    {
      "id": "N005",
      "category1": "Organic",
      "category2": "Health",
      "title": "Consumer demand for organic produce continues to soar",
      "image_source": "/image39.jpg",
      "image_alt": "Basket full of fresh organic vegetables",
      "link": "/news/organic-demand-growth",
    },
    {
      "id": "N006",
      "category1": "Policy",
      "category2": "Trade",
      "title": "New agricultural trade agreements open up international markets",
      "image_source": "/image40.jpg",
      "image_alt": "Hands shaking over a world map, symbolizing trade",
      "link": "/news/agri-trade-agreements",
    },
    {
      "id": "N007",
      "category1": "Innovation",
      "category2": "Livestock",
      "title": "Sensor technology improving animal welfare and farm productivity",
      "image_source": "/image41.jpg",
      "image_alt": "Cows grazing in a field with sensor tags",
      "link": "/news/livestock-sensor-tech",
    },
    {
      "id": "N008",
      "category1": "Climate",
      "category2": "Research",
      "title": "Study reveals impact of changing climate on regional crop yields",
      "image_source": "/image42.jpg",
      "image_alt": "Scientist examining plants in a lab with climate data overlay",
      "link": "/news/climate-crop-yield-study",
    },
  ];
  
  export default newsData;